# Generated by Django 3.1 on 2020-08-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('ip', models.CharField(default='', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
    ]
