# Generated by Django 3.1 on 2020-08-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0003_auto_20200828_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_ip',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
