# Generated by Django 3.1 on 2020-08-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0004_device_ip_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_ip',
            name='image',
        ),
    ]
