# Generated by Django 3.1 on 2020-08-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0005_remove_device_ip_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(default='', max_length=20)),
                ('imageMe', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
