# Generated by Django 3.1 on 2020-08-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0006_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='imageMe',
            field=models.ImageField(upload_to=''),
        ),
    ]
