# Generated by Django 3.0.8 on 2020-09-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0008_auto_20200829_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
