# Generated by Django 3.0.8 on 2020-09-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0009_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_ip',
            name='manager',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=50),
        ),
    ]
