# Generated by Django 3.0.8 on 2020-09-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0010_device_ip_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='manager',
            field=models.CharField(choices=[('admin', 'admin'), ('linhnh', 'linhnh'), ('phonght', 'phonght')], default='admin', max_length=50),
        ),
    ]
