# Generated by Django 3.0.8 on 2020-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0011_auto_20200924_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.BooleanField(default=True),
        ),
    ]
