# Generated by Django 3.0.8 on 2020-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0012_device_ip_enablemonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.BooleanField(default=False),
        ),
    ]
