# Generated by Django 3.0.8 on 2020-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0013_auto_20200927_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.BooleanField(),
        ),
    ]
