# Generated by Django 3.0.8 on 2020-09-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0016_auto_20200927_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.CharField(choices=[(1, 'running'), (0, 'stop')], default=1, max_length=20),
        ),
    ]
