# Generated by Django 3.0.8 on 2020-09-27 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0017_auto_20200927_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_ip',
            name='EnableMonitor',
        ),
    ]
