# Generated by Django 3.0.8 on 2020-09-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0020_remove_device_ip_enablemonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.CharField(choices=[('run', 'running'), ('stop', 'stop')], default=1, max_length=20),
        ),
    ]
