# Generated by Django 3.0.8 on 2020-09-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0021_device_ip_enablemonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.CharField(choices=[('run', 'running'), ('stop', 'stop')], default='run', max_length=20),
        ),
    ]
