# Generated by Django 3.0.8 on 2020-09-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0022_auto_20200928_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.CharField(choices=[('run', 'running'), ('stop', 'stoping')], default='run', max_length=20),
        ),
    ]
