# Generated by Django 3.0.8 on 2020-09-28 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0023_auto_20200928_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_ip',
            name='EnableMonitor',
        ),
    ]
