# Generated by Django 3.0.8 on 2020-09-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0024_remove_device_ip_enablemonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.CharField(choices=[('run', 'running'), ('stop', 'stoping')], default='run', max_length=20),
        ),
    ]
