# Generated by Django 3.0.8 on 2020-09-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0025_device_ip_enablemonitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.CharField(choices=[('run', 'running'), ('stop', 'stoping')], default='run', max_length=100),
        ),
        migrations.AlterField(
            model_name='device_ip',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
