# Generated by Django 3.0.8 on 2020-09-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0026_auto_20200928_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_ip',
            name='EnableMonitor',
        ),
    ]
