# Generated by Django 3.0.8 on 2020-09-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0029_remove_device_ip_enablemonitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='enable', max_length=100),
        ),
    ]
