# Generated by Django 3.0.8 on 2020-10-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0030_device_ip_enablemonitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
