# Generated by Django 3.0.8 on 2020-10-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0031_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(default='', max_length=100)),
                ('ip', models.CharField(default='', max_length=100)),
                ('cpu', models.CharField(default='', max_length=100)),
                ('ram', models.CharField(default='', max_length=100)),
                ('hardisk', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
