# Generated by Django 3.0.8 on 2020-10-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0032_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_ip',
            name='maker',
            field=models.CharField(choices=[('cisco', 'Cisco'), ('juniper', 'Juniper'), ('tp-link', 'Tp-link'), ('huawei', 'Huawei'), ('hkvision', 'Hkvision'), ('hp', 'HP'), ('fortinet', 'Fortinet'), ('other', 'Other')], default='other', max_length=200),
        ),
    ]
