# Generated by Django 3.0.8 on 2020-10-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0033_device_ip_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='maker',
            field=models.CharField(choices=[('Cisco', 'Cisco'), ('Juniper', 'Juniper'), ('Tp-link', 'Tp-link'), ('Huawei', 'Huawei'), ('Hkvision', 'Hkvision'), ('HP', 'HP'), ('Fortinet', 'Fortinet'), ('Other', 'Other')], default='other', max_length=200),
        ),
    ]
