# Generated by Django 3.0.8 on 2020-10-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0037_auto_20201012_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='manager',
            field=models.CharField(choices=[('admin', 'admin'), ('linhnh', 'linhnh'), ('phonght', 'phonght')], default='linhnh', max_length=50),
        ),
    ]
