# Generated by Django 3.0.8 on 2020-10-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0038_auto_20201012_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_ip',
            name='EnableMonitor',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=100),
        ),
        migrations.AlterField(
            model_name='device_ip',
            name='manager',
            field=models.CharField(choices=[('admin', 'admin'), ('Linhnh', 'Linhnh'), ('Phonght', 'Phonght')], default='linhnh', max_length=50),
        ),
    ]
