# Generated by Django 3.0.8 on 2020-10-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0040_auto_20201012_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_ip',
            name='DeviceType',
            field=models.CharField(choices=[('Router', 'Router'), ('Switch', 'Switch'), ('Firewall', 'Firewall'), ('Server', 'Server'), ('Modem', 'Modem'), ('Print', 'Print'), ('Camera', 'Camera'), ('Camera Record', 'Camera Record'), ('Database', 'Database'), ('Other', 'Other')], default='Other', max_length=200),
        ),
    ]
